### ISSUE TITLE
Error in : se.py, 23: x = multiply([init, se])"

### ISSUE THREAD

**Issue by luonango** [titu1994/keras-squeeze-excite-network#2]
I got a problem when I run   "x = multiply([init, se])" in se.py of line 23.
Could you tell me how to solve it ? thanks.
---------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/b3432/anaconda2/envs/Keras/lib/python2.7/site-packages/keras/layers/merge.py", line 468, in multiply
    return Multiply(**kwargs)(inputs)
  File "/home/b3432/anaconda2/envs/Keras/lib/python2.7/site-packages/keras/engine/topology.py", line 571, in __call__
    self.build(input_shapes)
  File "/home/b3432/anaconda2/envs/Keras/lib/python2.7/site-packages/keras/layers/merge.py", line 84, in build
    output_shape = self._compute_elemwise_op_output_shape(output_shape, shape)
  File "/home/b3432/anaconda2/envs/Keras/lib/python2.7/site-packages/keras/layers/merge.py", line 55, in _compute_elemwise_op_output_shape
    str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (64, 48, 48) (64, 1, 64)
----------------------

**Comment by titu1994** [comment]
I haven't set it up for channels first dim ordering yet. That's the reason it fails. Will fix in a few days.

**Comment by luonango** [comment]
ok, and thank you for sharing this code O_o

**Comment by titu1994** [comment]
Fixed via f27a8636296a9313de3e0ee043df31b9807517ce.
